sudo: required
language: node_js
node_js:
  - "4.1"

services:
  - docker

before_install:
  - 'sudo apt-get purge -y lxc-docker docker-engine'
  - 'curl -sSL https://get.docker.com/ | sh'
  - 'docker --version'
  - 'sudo docker build -t singpath/verifier2:latest .'
  - 'sudo docker build -t singpath/verifier2-python:latest ./verifiers/python'
  - 'sudo docker build -t singpath/verifier2-java:latest ./verifiers/java'
  - 'sudo docker build -t singpath/verifier2-javascript:latest ./verifiers/javascript'

script:
  - npm run lint
  - npm test
  - npm run coveralls
  - 'sudo docker run -ti --rm -e SKIP_BUILD=1 -v /var/run/docker.sock:/var/run/docker.sock --group-add `cat /etc/group | grep "^docker" | cut -d: -f3` singpath/verifier2:latest verifier test "$(cat ./examples/tests.yaml)"'
